-- =============================================
-- SaveToDB Sample 13 for Snowflake - Tests
-- Version 10.13, April 29, 2024
--
-- Copyright 2021-2024 Gartle LLC
--
-- License: MIT
-- =============================================

CREATE USER SAMPLE13_USER1 PASSWORD='Usr_2011#_Xls4168';

CREATE ROLE SAMPLE13_USERS;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SAMPLE13_USERS;
GRANT USAGE ON SCHEMA S13           TO ROLE SAMPLE13_USERS;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES      IN SCHEMA S13 TO ROLE SAMPLE13_USERS;
GRANT SELECT                         ON ALL VIEWS       IN SCHEMA S13 TO ROLE SAMPLE13_USERS;
GRANT USAGE                          ON ALL FUNCTIONS   IN SCHEMA S13 TO ROLE SAMPLE13_USERS;
GRANT USAGE                          ON ALL PROCEDURES  IN SCHEMA S13 TO ROLE SAMPLE13_USERS;

GRANT ROLE SAMPLE13_USERS       TO USER SAMPLE13_USER1;

ALTER USER SAMPLE13_USER1 SET DEFAULT_ROLE=SAMPLE13_USERS;

ALTER USER SAMPLE13_USER1 SET DEFAULT_WAREHOUSE='COMPUTE_WH';
