-- =============================================
-- SaveToDB Sample 02 for Snowflake - Advanced Features
-- Version 10.6, December 13, 2022
--
-- Copyright 2018-2022 Gartle LLC
--
-- License: MIT
-- =============================================

DELETE FROM XLS.FORMATS         WHERE TABLE_SCHEMA IN ('S02');
DELETE FROM XLS.HANDLERS        WHERE TABLE_SCHEMA IN ('S02');
DELETE FROM XLS.OBJECTS         WHERE TABLE_SCHEMA IN ('S02');
DELETE FROM XLS.TRANSLATIONS    WHERE TABLE_SCHEMA IN ('S02');
DELETE FROM XLS.WORKBOOKS       WHERE TABLE_SCHEMA IN ('S02');

DROP USER SAMPLE02_USER1;
DROP USER SAMPLE02_USER2;
DROP USER SAMPLE02_USER3;

DROP ROLE SAMPLE02_ADV_USERS;
DROP ROLE SAMPLE02_XLS_USERS;
DROP ROLE SAMPLE02_USERS;

DROP FUNCTION S02.USP_CASHBOOK(int, int, int);

DROP VIEW S02.VIEW_CASHBOOK;
DROP VIEW S02.VIEW_CASHBOOK2;
DROP VIEW S02.VIEW_CASHBOOK3;

DROP TABLE S02.CASHBOOK;
DROP TABLE S02.ITEM_COMPANIES;
DROP TABLE S02.ITEMS;
DROP TABLE S02.ACCOUNTS;
DROP TABLE S02.COMPANIES;

DROP SCHEMA S02;

-- print Application removed
